---
- name: Default Packages
  hosts: all
  tags: ubuntu 
  tasks:
    - name: Apt packages
      apt:
       name="{{item}}"
       state=present
      become: yes
      with_items:
        - vim
        - chromium-browser
        - zsh
        - curl
        - wget
        - git
        - python3
        - python-virtualenv
        - python-pip
        - virtualbox
        - virtualbox-dkms
        - tlp
        - tlp-rdw
        - tmux

- name: Default homebrew packages mac
  hosts: install
  tags: mac
  tasks:
    - name: Install homebrew packages
      shell: brew install {{item}}
      with_items:
        - asdf
        - awscli
        - azure-cli
        - coreutils
        - devspace
        - direnv
        - findutils
        - gnu-sed
        - gnupg
        - helm
        - helmfile
        - jq
        - k9s
        - kubent
        - nmap
        - poetry
        - pyyaml
        - sqlite
        - telnet
        - tflint
        - tmux
        - virtualenv
        - yamllint
        - yq

    - name: Download dmgs
      hosts: all
      tags: mac
      tasks:
        - name: download sublime
          get_url: https://download.sublimetext.com/Sublime%20Text%20Build%203211.dmg
          dest: ~/Downloads/sublime.dmg

        - name: Download Joplin m1
          get_url: https://objects.joplinusercontent.com/v2.14.20/Joplin-2.14.20-arm64.DMG
          dest: ~/Downloads/joplin.dmg

        - name: timeular m1
          get_url: https://releases.timeular.com/mac/production/Timeular-m1.dmg
          dest: ~/Downloads/timeular.dmg


- name: oh-my-zsh install
  hosts: all
  tags: zsh
  tasks:
    - name: clone
      git:
        clone: yes
        dest: "~/.oh-my-zsh"
        repo: "https://github.com/robbyrussell/oh-my-zsh.git"

    - name: zshrc
      copy:
        src: files/zsh/zshrc
        dest: "~/.zshrc"

    - name: omz theme
      copy:
        src: "files/zsh/david-clean.zsh-theme"
        dest: "~/.oh-my-zsh/themes/david-clean.zsh-theme"

    - name: omz theme
      copy:
        src: "files/zsh/clean.zsh-theme"
        dest: "~/.oh-my-zsh/themes/work-clean.zsh-theme"


    - name: set shell
      user: name="{{ansible_user_id}}" shell="/bin/zsh"
      become: yes

- name: Joplin install
  hosts: all
  tags: mac
  tasks:
    - name: install joplin



- name:  Other Configs
  hosts: all
  tags: other
  tasks:
    - name: vimrc
      copy:
        src: files/vimrc
        dest: "~/.vimrc"

    - name: tmux config 
      copy: 
        src: "files/tmux.conf"
        dest: "~/.tmux.conf"
