---
- name: Default Packages
  hosts: localhost
  tags: ubuntu 
  tasks:
    - name: Apt packages
      apt:
       name="{{item}}"
       state=present
      become: yes
      with_items:
        - vim
        - chromium-browser
        - zsh
        - curl
        - wget
        - git
        - python3
        - python3-virtualenv
        - python3-pip
        - virtualbox
        - virtualbox-dkms
        - tlp
        - tlp-rdw
        - tmux
        - jq
        - apt-transport-https
        - xclip

- name: Default homebrew packages mac
  hosts: localhost
  tags: mac
  tasks:
    - name: Install host homebrew packages
      shell: /opt/homebrew/bin/brew install {{item}}
      with_items:
        - asdf
        - awscli
        - azure-cli
        - coreutils
        - devspace
        - direnv
        - findutils
        - gnu-sed
        - gnupg
        - helm
        - helmfile
        - jq
        - k9s
        - kubent
        - nmap
        - poetry
        - pyyaml
        - sqlite
        - telnet
        - teleport
        - tflint
        - tmux
        - virtualenv
        - watch
        - yamllint
        - yq

- name: Download dmgs
  hosts: localhost
  tags: mac
  tasks:
    - name: download sublime
      get_url: 
        url: https://download.sublimetext.com/Sublime%20Text%20Build%203211.dmg
        dest: ~/Downloads/sublime.dmg

    - name: Download Joplin m1
      get_url: 
        url: https://objects.joplinusercontent.com/v2.14.20/Joplin-2.14.20-arm64.DMG
        dest: ~/Downloads/joplin.dmg

    - name: timeular m1
      get_url: 
         url: https://releases.timeular.com/mac/production/Timeular-m1.dmg
         dest: ~/Downloads/timeular.dmg

    # TODO:
    # Rectangle
    # firefox
    # Docker-desktop: https://desktop.docker.com/mac/main/arm64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=dd-smartbutton&utm_location=module&_gl=1*okw98w*_ga*MTkwNDYwMjg5Ny4xNzEyMDgxMTUx*_ga_XJWPQMJYHQ*MTcxMjA4MTE1MC4xLjEuMTcxMjA4MTE1NC41Ni4wLjA.
    # Spotify

    # TODO: disable hold key for accented mark
    # defaults write -g ApplePressAndHoldEnabled -bool false

- name: Install Sublime Text 
  hosts: localhost
  tags: ubuntu
  become: yes
  tasks: 
  - name: Install GPG Key
    ansible.builtin.apt_key: 
      keyserver: https://download.sublimetext.com/sublimehq-pub.gpg
      id: ADAE6AD28A8F901A
  
  - name: update Apt config 
    ansible.builtin.copy: 
       content: "deb https://download.sublimetext.com/ apt/stable/"
       dest: "/etc/apt/sources.list.d/sublime-text.list"
        
  - name: Install Sublime Text
    apt: 
      update_cache: true
      pkg: 
        - sublime-text
       
  - name: Install Obsidian 
    ansible.builtin.command: snap install --classic obsidian
    
- name: oh-my-zsh install
  hosts: localhost
  tags: zsh
  tasks:
    - name: clone
      git:
        clone: yes
        dest: "~/.oh-my-zsh"
        repo: "https://github.com/robbyrussell/oh-my-zsh.git"

    - name: zshrc
      copy:
        src: files/zsh/zshrc
        dest: "~/.zshrc"

    - name: omz theme
      copy:
        src: "files/zsh/david-clean.zsh-theme"
        dest: "~/.oh-my-zsh/themes/david-clean.zsh-theme"

    - name: omz theme
      copy:
        src: "files/zsh/clean.zsh-theme"
        dest: "~/.oh-my-zsh/themes/work-clean.zsh-theme"


    - name: set shell
      user: name="{{ansible_user_id}}" shell="/bin/zsh"
      become: yes

#- name: Joplin instlocalhost
#  hosts: localhost
#  tags: mac
#  tasks:
#    - name: instlocalhost joplin



- name:  Other Configs
  hosts: localhost
  tags: other
  tasks:
    - name: vimrc
      copy:
        src: files/vimrc
        dest: "~/.vimrc"

    - name: tmux config 
      copy: 
        src: "files/tmux.conf"
        dest: "~/.tmux.conf"
